### ISSUE TITLE
Kate5 Support

### ISSUE THREAD

**Issue by yakusha** [eMerzh/kate-twig#5]
Syntax folder path changed with kate5...

New path is /home/USER/.local/share/katepart5/syntax/

**Comment by eMerzh** [comment]
Thanks I've added a note to the readme ... but i have no idea how to efficiently install it to the correct directory(ies) .... suggestions?

**Comment by rla** [comment]
I suggest to install system-wide and run search for existing known syntax files. The location seems to be very inconsistent between different systems. Example:

```
$ find /usr -iname "katetemplate.xml"
/usr/share/apps/katepart/syntax/katetemplate.xml
```
